### ISSUE TITLE
Plated Elytra - Geyser

### ISSUE THREAD

**Issue by SavageTheUnicorn** [mrmelon54/armored_elytra#10]
I'm using Geyser and Floodgate on a 1.19.4 fabric server with Plated Elytra and your mod installed. I'm only seeing an elytra with data/lore added to indicate it's fused. No armor is visible. I will check on Java edition in a few hours or so and update with results here later.

**Comment by MrMelon54** [comment]
This mod only works client side, and I'm pretty sure it won't install into a Bedrock edition client. Trying to use the mod in the server either crashes or does nothing (depending on which one of my mods is used).
