### ISSUE TITLE
Minecraft Crashes when joining world

### ISSUE THREAD

**Issue by Tri-Iris** [mrmelon54/armored_elytra#13]
[crash-2024-01-24_19.25.18-client.txt](https://github.com/mrmelon54/armored_elytra/files/14046396/crash-2024-01-24_19.25.18-client.txt)

**Comment by Tri-Iris** [comment]
I forgot to mention that this was on the newest version of the mod.

**Comment by mrmelon54** [comment]
Is this resolved in [1.0.2](https://modrinth.com/mod/armored-elytra/version/1.0.2)

**Comment by Tri-Iris** [comment]
I use the 1.20.2 minecraft version of the game

**Comment by mrmelon54** [comment]
https://mclo.gs/s9d71y6

**Comment by mrmelon54** [comment]
@Tri-Iris try the latest 1.20.2 build
