### ISSUE TITLE
Compatibility request: Voodoo Armored Elytra

### ISSUE THREAD

**Issue by Felina-Lain** [mrmelon54/armored_elytra#2]
Hello, just to ask if you would consider making it compatible with https://mc.voodoobeard.com/#plated_elytra as well as the vanilla tweaks?

**Comment by MrMelon54** [comment]
It should already be compatible with voodoobeard plated elytra

**Comment by Felina-Lain** [comment]
I might have setup something wrong then, because I'm using plated elytra and the mod, and I still only get elytra visuals, instead of an armor with elytra on it. Is there any setting that need to be done upon install? Activation? Permissions?
Or is it maybe not compatible with servers using that datapack? (I'm using the pack on a server with friends)

**Comment by MrMelon54** [comment]
Weird I'll take a look into it

**Comment by mrmelon54** [comment]
Can't reproduce
