### ISSUE TITLE
Other player's armor trims render inside my vision

### ISSUE THREAD

**Issue by sailboat3** [MrMelon54/armored_elytra#3]
Me and my friends play on a server with the Vanilla Tweaks armored elytra datapack, and their armored elytra has an armor trim. Whenever I look at one of my friends, the armor trim does not appear on the chestplate and instead renders directly on my camera. If I look away, the trim disappears. I am playing on fabric 1.20.1 with the latest version of this mod. 

Here is a screenshot:
![2023-08-04_12 47 59](https://github.com/MrMelon54/armored_elytra/assets/115509970/6ec61bfe-10dc-4c08-a3f4-c19264368873)

**Comment by MrMelon54** [comment]
This is probably an incompatibility with another mod. Can you try removing each mod until it works fine.

A good start would be anh mod which edit armor or rendering.

**Comment by MrMelon54** [comment]
Could I at least get some information about which mod could be causing the issue to resolve the incompatibility?

**Comment by sailboat3** [comment]
It appears that Immediately Fast was causing the issue.

**Comment by MrMelon54** [comment]
related to: #1

**Comment by sailboat3** [comment]
Yes, I should have looked there before posting this. Thank you for helping me.

**Comment by MrMelon54** [comment]
yeah no worries
