### ISSUE TITLE
Trims do not show on chestplate when combined

### ISSUE THREAD

**Issue by mcneds** [mrmelon54/armored_elytra#9]
![image](https://github.com/MrMelon54/armored_elytra/assets/73141306/95a48d41-b5aa-482c-9b61-6ddfd0fd3798)

above you can see that it is rendered in 3rd person but like on the screen?? idk why

**Comment by mcneds** [comment]
it sorta show up moving around the edges

**Comment by mrmelon54** [comment]
what mods are you playing with?

**Comment by mrmelon54** [comment]
work fine for me in the latest version
